services:
  postgres:
    image: postgres:16-alpine
    platform: linux/arm64
    container_name: urlshortener-postgres
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d urlshortener"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - urlshortener-network

  redis:
    image: redis:7-alpine
    platform: linux/arm64
    container_name: urlshortener-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru --tcp-keepalive 60 --timeout 0 --ignore-warnings ARM64-COW-BUG
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - urlshortener-network

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    platform: linux/arm64
    container_name: urlshortener-redis-ui
    environment:
      REDIS_HOSTS: local:redis:6379
      HTTP_USER: admin
      HTTP_PASSWORD: admin
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - urlshortener-network

  supabase-studio:
    image: supabase/studio:latest
    platform: linux/arm64
    container_name: urlshortener-studio
    ports:
      - "8080:3000"
    environment:
      SUPABASE_URL: http://localhost:3000
      SUPABASE_REST_URL: http://localhost:3000/rest/v1/
      POSTGRES_PASSWORD: postgres
      DEFAULT_ORGANIZATION_NAME: "URL Shortener"
      DEFAULT_PROJECT_NAME: "Development"
      SUPABASE_PUBLIC_URL: http://localhost:8080
    depends_on:
      - postgres
    networks:
      - urlshortener-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local



networks:
  urlshortener-network:
    driver: bridge